apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind-deployment
  labels:
    app: bind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind
  template:
    metadata:
      labels:
        app: bind
    spec:
      containers:
      - name: bind
        image: internetsystemsconsortium/bind9:9.20
        env:
        - name: DOCKER_LOGS
          value: 1
        - name: ALLOW_QUERY
          value: any
        ports:
        - containerPort: 53
