apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-config
data:
  named.conf: |
    acl "trusted" {
        10.55.12.0/24;
    };
    
    options {
            directory "/var/cache/bind";
            listen-on port 53 { any; };
            auth-nxdomain yes;
            forwarders { 
                    1.1.1.1; 
                    1.0.0.1; 
            };
            listen-on-v6 { ::1; };
            allow-recursion {
                    trusted;
            };
            allow-transfer {
                    none;
            };
            allow-update {
                    none;
            };
    };

    key "externaldns" {
        algorithm hmac-sha256;
        secret "g3+uS+rPS9bBnRtGmUfpXWxIL+KDCTCJKD+Jhiuo8H8=";
    };

    zone "tridentcloud.dev" {
        type primary;
        file "/etc/bind/zones.tridentcloud.dev";
        allow-transfer {
            key "externaldns";
        };
        update-policy {
            grant externaldns zonesub ANY;
        };
    };
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind-zone-config
data:
{{- toYaml .Values.bindzones | nindent 2 }}
