apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
      - name: bind9
        image: ubuntu/bind9:9.18-22.04_beta
        env:
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP       
        volumeMounts:
        - name: bind-zone-config
          mountPath: /var/lib/bind
      volumes:
      - name: bind-zone-config
        configMap:
          name: bind-zone-config
            zoneconfigs:
            items:                 
            - key: c00lz0ne.internal
              path: c00lz0ne.internal
