apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: bind
  template:
    metadata:
      labels: 
        app: bind
    spec:
      containers:
      - name: bind
        image: internetsystemsconsortium/bind9:9.20
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        volumeMounts:
        - name: bind-config
          mountPath: /etc/bind
        - name: bind-zone-config
          mountPath: /var/lib/bind
      volumes:
        - name: bind-config
          configMap:
            name: bind-config
            items:
              - key: named.conf
                path: named.conf
        - name: bind-zone-config
          configMap:
            name: bind-zone-config
            items:                 
              - key: tridentcloud.dev
                path: tridentcloud.dev
