apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  labels:
    app: bind9
spec:
  type: NodePort
  selector:
    app: bind9
  ports:
  - protocol: TCP
    port: 53
    targetPort: 53
    name: bind9-tcp
  - protocol: UDP
    port: 53
    targetPort: 53
    name: bind9-udp
