apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  labels:
    app: bind9
spec:
  selector:
    app: bind9
  ports:
  - protocol: TCP
    port: 5353
    targetPort: 53
    name: bind9-tcp
  - protocol: UDP
    port: 5353
    targetPort: 53
    name: bind9
    volumeMounts:
        - name: bind-zone-config
          mountPath: /var/lib/bind
volumes:
  - name: bind-zone-config
  configMap:
    name: bind-zone-config
    zoneconfigs:
      items:                 
        - key: c00lz0ne.internal
          path: c00lz0ne.internal
